GET http://localhost:3000/api/categories

###

GET http://localhost:3000/api/categories/6593ede7ad4bf20a16e96bbc

###

POST http://localhost:3000/api/categories/create
Content-Type: application/json

{
    "category": "newcat"
}

###

DELETE http://localhost:3000/api/categories/65bcdc4f02ea55780a630c44
