GET http://localhost:3000/api/categories

###

GET http://localhost:3000/api/categories/6593f55592952be70faf9abd

###

POST http://localhost:3000/api/categories/create
Content-Type: application/json

{
    "category": "adventure"
}

###

DELETE http://localhost:3000/api/categories/6593f55592952be70faf9abd
