### // GET ALL CUSTOMERS
GET http://localhost:3000/api/customers


### // GET ONE CUSTOMER
GET http://localhost:3000/api/customers/658ec9cc1c59f85c65b7c84a


### // CREATE A NEW CUSTOMER
POST http://localhost:3000/api/customers/create
Content-Type: application/json

{
    "mail": "delete4@user.com",
    "password": "12345"
}


### // LOGIN ADMIN
POST http://localhost:3000/api/customers/login
Content-Type: application/json

{
"mail": "admin@admin.com",
"password": "12345"
}


### // EDIT CUSTOMER
POST http://localhost:3000/api/customers/edit-customer/658ecd718cee95807c699848
Content-Type: application/json

{
    "mail": "delete4@user.com",
    "password": "$2b$15$AwiwCmyDeIbJ/BUg2N06vOUTYVyRX6ssu3z8yvGDcthoSwdZL8CSG",
    "isAdmin": false,
    "orders": [],
    "joinDate": "2023-12-29T13:03:26.833Z",
    "address": [{
        "_id": "mainaddress",
        "street": "Road 30",
        "zip": 1234,
        "county": 1234,
        "halleoluja":"hello"
    }]
}


### // LOGOUT CUSTOMER
POST http://localhost:3000/api/customers/logout


### // DELETE CUSTOMER
DELETE http://localhost:3000/api/customers/delete/658ecba6c36a18b6a863fe95