### // GET ALL CUSTOMERS
GET http://localhost:3000/api/customers


### // GET ONE CUSTOMER
GET http://localhost:3000/api/customers/65bcdb5602ea55780a630c35


### // CHECKS FOR ACTIVE USER
GET http://localhost:3000/api/customers/active


### // CREATE A NEW CUSTOMER
POST http://localhost:3000/api/customers/create
Content-Type: application/json

{
    "mail": "newUser123@yahoo.com",
    "password": "12345"
}


### // LOGIN USER
POST http://localhost:3000/api/customers/login
Content-Type: application/json

{
"mail": "newuser@yahoo.com",
"password": "12345"
}

### // LOGIN ADMIN
POST http://localhost:3000/api/customers/login
Content-Type: application/json

{
"mail": "admin@admin.com",
"password": "12345"
}


### // EDIT CUSTOMER
POST http://localhost:3000/api/customers/edit-customer/65bcdb5602ea55780a630c35
Content-Type: application/json

{
    "address": [{
        "_id": "line1",
        "street": "street",
        "zip": "zip",
        "city": "city"
    }],
    "username": "earl-pearl"
}


### // LOGOUT CUSTOMER
POST http://localhost:3000/api/customers/logout


### // DELETE CUSTOMER
DELETE http://localhost:3000/api/customers/delete/65bcdc0602ea55780a630c3b