### // GET ALL CUSTOMERS
GET http://localhost:3000/api/customers


### // GET ONE CUSTOMER
GET http://localhost:3000/api/customers/65bcb48dc64afdfd02708ed3


### // CHECKS FOR ACTIVE USER
GET http://localhost:3000/api/customers/active


### // CREATE A NEW CUSTOMER
POST http://localhost:3000/api/customers/create
Content-Type: application/json

{
    "mail": "newUser@yahoo.com",
    "password": "12345"
}


### // LOGIN USER
POST http://localhost:3000/api/customers/login
Content-Type: application/json

{
"mail": "newuser@yahoo.com",
"password": "12345"
}

### // LOGIN ADMIN
POST http://localhost:3000/api/customers/login
Content-Type: application/json

{
"mail": "admin@admin.com",
"password": "12345"
}


### // EDIT CUSTOMER
POST http://localhost:3000/api/customers/edit-customer/65bcb7a312e7e115e56d9eb9
Content-Type: application/json

{
    "mail": "newuser123@yahoo.com",
    "username": "jusdyTrudy"
}


### // LOGOUT CUSTOMER
POST http://localhost:3000/api/customers/logout


### // DELETE CUSTOMER
DELETE http://localhost:3000/api/customers/delete/65a2a68e50d7dda54e90e32f