GET http://localhost:3000/api/orders

###

GET http://localhost:3000/api/orders/user-orders/6596c71ee62bf4f20da2ebcf

###

GET http://localhost:3000/api/orders/659bdf345234d267f4f1bcf0

###

POST http://localhost:3000/api/orders/create
Content-Type: application/json

{
    "customer": "659fe78583e4a05d0755f06a",
    "order": [{ "product": "65983b80ad42eae475e37524", "quantity": 32}, { "product": "659827dd39cc31ac1bf1dc1d", "quantity": 2} ],
    "total_price": 12229,
    "discount": 0
}

###

POST http://localhost:3000/api/orders/create-checkout-session
Content-Type: application/json

[
{
      "price": "price_1OY9H6G8mk548Xri9gY7CUXI",
      "quantity": 2
    }
]

###

PUT http://localhost:3000/api/orders/manage-order/65a2a5bd50d7dda54e90e324
Content-Type: application/json

{
    "payment_status": "paid"
}

###

DELETE http://localhost:3000/api/orders/delete/659bddc50a1556021d517e31
