GET http://localhost:3000/api/orders

###

GET http://localhost:3000/api/orders/user-orders

###

GET http://localhost:3000/api/orders/65b2b07ca27f0db6a29d942a

###

POST http://localhost:3000/api/orders/create
Content-Type: application/json

{
    "sessionId": "cs_test_b1IBZd1rTyrdNdUdAYkju3UJAs6QWuOkBqzqECuyUBPrl4EUOh3X7BwX9E",
    "order" : {
        "order": [{ "product": "65a2ae3d719aaaf33cdf52cf", "quantity": 32, "digital": false, "vhs": true}, { "product": "65a2b128719aaaf33cdf52e3", "quantity": 2, "digital": false, "vhs": true} ],
        "total_price": 12229,
        "discount": 0
    }
}

###

POST http://localhost:3000/api/orders/create-checkout-session
Content-Type: application/json

[
{
      "price": "price_1OY9H6G8mk548Xri9gY7CUXI",
      "quantity": 2
    }
]

###

PUT http://localhost:3000/api/orders/manage-order/65b9854eebac6edeb0c59be7
Content-Type: application/json

{
    "shipped": true
}

###

DELETE http://localhost:3000/api/orders/delete/659bddc50a1556021d517e31
