GET http://localhost:3000/api/products

###

GET http://localhost:3000/api/products/65982b6bf5a6f314600b4779

###

POST http://localhost:3000/api/products/create
Content-Type: application/json

{
    "title": "Tarzan",
    "description": "A dog on the loose is the Postman's worst nightmare ",
    "category": ["6593ee75ad4bf20a16e96bc1"],
    "tags": ["659424b2d79e7cd5a3489d7f"],
    "year": 1990,
    "vhs": {
        "price": 29,
        "available": true,
        "quantity": 5,
        "inStock": 5
    },
    "digital": {
        "price": 39,
        "available": true
    }
}

###

POST http://localhost:3000/api/products/edit-product/65943006164884dad74d3222
Content-Type: application/json

{
    "title": "new movie about something",
    "description": "its a very new movie",
    "category": ["6593ee75ad4bf20a16e96bc1"],
    "tags": ["659424b2d79e7cd5a3489d7f"],
    "year": 1990,
    "vhs": {
        "price": 29,
        "available": true,
        "quantity": 10,
        "inStock": 5
    },
    "digital": {
        "price": 49,
        "available": true
    }
}

###

DELETE http://localhost:3000/api/products/delete/65982b6bf5a6f314600b4779