GET http://localhost:3000/api/products

###

GET http://localhost:3000/api/products/65a2b315719aaaf33cdf52f4

###

POST http://localhost:3000/api/products/create
Content-Type: application/json

{
    "title": "newMovie22",
    "description": "rickityehfakajfasl dsai fkwoa owa aw ",
    "category": ["6593ee75ad4bf20a16e96bc1", "6593efd0a62dd39fcfa68fbf"],
    "tags": ["65a2cd1b6f8b84b920cdc6e9", "65a2cd9a6f8b84b920cdc6f0", "65a2cdb06f8b84b920cdc6f3"],
    "content_rating": "PG-13",
    "rating": 4,
    "year": 2009,
    "image": "https://www.themoviedb.org/t/p/w500/aEqtJDj8MvSDQwzggvcOfFTZMw.jpg",
    "vhs": {
        "price": 29,
        "available": true,
        "quantity": 6,
        "inStock": 6
    },
    "digital": {
        "price": 29,
        "available": true
    }
}

###

PUT http://localhost:3000/api/products/edit-product/65bce0b996c13f81ce44170e
Content-Type: application/json

{
"vhs": {
        "price": 249,
        "available": true,
        "quantity": 7,
        "inStock": 6,
        "stripe_prod_id": "prod_PMvEWoHeQ9PcEO"
    },
    "title": "newMovie44"
}

###

DELETE http://localhost:3000/api/products/delete/65bce0b996c13f81ce44170e