GET http://localhost:3000/api/tags

###

GET http://localhost:3000/api/tags/65a2be2d6f8b84b920cdc649

###

POST http://localhost:3000/api/tags/create
Content-Type: application/json

{
    "tag": "ryan reynolds"
}

###

DELETE http://localhost:3000/api/tags/65a2a071b4ff867e76bc6b4e
