GET http://localhost:3000/api/tags

###

GET http://localhost:3000/api/tags/65942464d79e7cd5a3489d70

###

POST http://localhost:3000/api/tags/create
Content-Type: application/json

{
    "tag": "jude"
}

###

DELETE http://localhost:3000/api/tags/65a2a071b4ff867e76bc6b4e
